version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"
      - "16686:16686"
    command:
      # host-portで0.0.0.0を指定しないとlocalhostで受け付けてしまうため、コンテナ外からアクセスできない
      - --collector.otlp.grpc.host-port=0.0.0.0:4317
